services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka_net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:  # Добавляем healthcheck для ZooKeeper
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  kafka:
    image: bitnami/kafka:3.7.0
    environment:
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_NODE_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CLIENT://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,CLIENT://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
    ports:
      - "9092:9092"
    networks:
      - kafka_net
    depends_on:
      zookeeper:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - kafka_net
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/kafka.xml  # Конфиг для Kafka
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # SQL для инициализации

networks:
  kafka_net:
    driver: bridge
